<a href="https://colab.research.google.com/github/joaoholandaa/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Numpy**

In [1]:
import os
import numpy as np
import pandas as pd

from pathlib import Path

%config Completer.use_jedi = False

##**Criação**<br>
Array são objetos que armazenam estruturas sequênciais de dados de tipo e tamanhos determinados que apontam para uma sequência de dados na memória RAM. Em Python, a biblioteca que lida com essas estruturas é o Numpy que não só oferece as funcionalidades clássicas de um array (que pode ser vistas em C, C++, Java...), mas também propriedades vetoriais utilizadas em operações em álgebra linear. <br> <br>
Criar um array é uma tarefa simples, que pode ser realizada por meio de uma lista como abaixo.

In [2]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [3]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

Ao fazer isso estaremos alocando os valores selecionados dentro da RAM do computador em endereços sequênciais, igualmente espaçados de acordo com o tipo de dado do array.<br><br>

Dado isso, é fácil perceber que um array tem as seguintes características que podem ser acessadas na forma de atributos deste objeto:

- dtype: O tipo de dados do array
- shape: O tamanho do array em linhas e colunas
- size: O tamanho do array em quantidade de elementos
- itemsize: O consumo de memória de cada elemento do array (em bytes)
- strides: Uma distancia em bytes entre os elementos armazenados na memória

In [4]:
print(
    f"array: dtype={array.dtype} | shape={array.shape} | size={array.size} "
    f"| itemsize={array.itemsize} | strides={array.strides}"
)

print(
    f"matriz: dtype={matriz.dtype} | shape={matriz.shape} | size={matriz.size} "
    f"| itemsize={matriz.itemsize} | strides={matriz.strides}"
)

array: dtype=int64 | shape=(5,) | size=5 | itemsize=8 | strides=(8,)
matriz: dtype=int64 | shape=(2, 3) | size=6 | itemsize=8 | strides=(24, 8)


Dado que inicializações de diferentes tipos de array são bastante comuns, a biblioteza contém uma série de funcionalidades que permitem criar arrays com diferentes tipos de dados. <br><br>
**np.zeros** -> Cria um array preenchido com zeros.

In [5]:
np.zeros(shape=(3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

**np.ones** -> Cria um array preenchido com "um's".

In [6]:
np.ones(shape=(3, ))

array([1., 1., 1.])

**np.eye** -> Cria a matriz identidade com o tamanho especificado.

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**np.arange** -> Mesma coisa que a função range, só que para arrays.

In [8]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

**np.linspace** -> Cria um array entre dois números espaçados linearmente.

In [9]:
np.linspace(5, 10, num=5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

**np.logspace** -> Cria um array entre dois números espaçados logaritmicamente.

In [10]:
np.logspace(0, 1, 3)

array([ 1.        ,  3.16227766, 10.        ])

**np.random.int** -> Cria um array de valores aleatórios entre um valor menor e maior (exclusivo).

In [11]:
np.random.randint(0, 10, size=(5,5))

array([[3, 8, 3, 0, 0],
       [4, 5, 2, 8, 9],
       [6, 8, 2, 4, 2],
       [3, 1, 3, 2, 4],
       [3, 8, 6, 3, 0]])

**np.random.normal** -> Cria um array aleatório com valores baseados em uma distribuição normal.

In [12]:
np.random.normal(1, 2, 10)

array([ 3.82204266,  3.30755498,  3.95601352, -0.89719341, -0.74344077,
        1.29507462,  0.68625026,  4.3287014 ,  4.36491058,  2.58302165])

É interessante notar que algumas dessas funções não permitem passar o tamanho do array (como o np.arange), por muitas vezes é comum combiná-las com o método reshape.

In [13]:
a = np.arange(12)
a = a.reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

##**Tipagem**<br>
Uma das diferenças mais gritantes entre arrays e listas é sua tipagem. Enquanto listas podem conter múltiplos tipos de dados (inteiros, strings, floats, etc) arrays tendem a tipagem fixa e tal tipagem pode ser modificda utilizando o método astype.

In [14]:
arr = np.array([1, 2, 3])
print(arr.dtype, arr)

int64 [1 2 3]


##**Indexação**<br>
Tal como listas os arrays são objetos indexáveis de maneira similar, de forma que a sintaxe de chaves e os slices funcionam normalmente.


In [15]:
array = np.arange(1, 10)
matriz = np.random.normal(1, 2, (3, 3))

print(array)
print(matriz)

[1 2 3 4 5 6 7 8 9]
[[ 2.6716372   1.17422732  1.99771282]
 [ 1.31420914  0.6916707   1.65603843]
 [ 1.36549891 -0.60187732  3.24454024]]


In [16]:
array[0]

1

In [17]:
matriz[2][-1]

3.2445402383774686

In [18]:
matriz[1]

array([1.31420914, 0.6916707 , 1.65603843])

In [19]:
array[::2]

array([1, 3, 5, 7, 9])

Entretanto o Numpy oferece uma maneira adicional de indexar elementos selecionando múltiplos índices por meio de uma lista.

In [20]:
array[1:3]

array([2, 3])

In [21]:
array[[1, 2]]

array([2, 3])

Por fim, Numpy oferece a flexibilidade, especialmente com matrizes, de selecionar os elementos de linhas e colunas em conjunto por meio da sintaxe de "," na qual fornecemos dois slices, o primeiro selecionando linhas e o segundo selecionando colunas.

In [22]:
matriz[:, 1]

array([ 1.17422732,  0.6916707 , -0.60187732])

In [23]:
matriz[1, 2]

1.6560384303040094

In [24]:
matriz[:, [1, 2]]

array([[ 1.17422732,  1.99771282],
       [ 0.6916707 ,  1.65603843],
       [-0.60187732,  3.24454024]])

In [25]:
arr = np.array([1, 2, 3])
arr = arr.astype("float")
print(arr.dtype, arr)

float64 [1. 2. 3.]


In [26]:
arr = np.array([1, 2, 3], dtype=np.uint8)
print(arr.dtype, arr)

uint8 [1 2 3]


In [27]:
arr = np.array(["olá", 2.1, [2, 3, 4]], dtype="object")
arr.shape

(3,)

##**Mutabilidade**<br>
Diferente de listas arrays são objetos imutáveis em tamanho e tipo (como visto acima, para mudar o tipo de array é criado um novo).


In [28]:
arr = np.array([1, 2, 3])
'''
arr.append(4)
Gera um erro!
'''

'\narr.append(4)\nGera um erro!\n'

Entretanto, diferente de tuplas, arrays são mútaveis em conteúdo.

In [29]:
arr[2] = 5
arr

array([1, 2, 5])

Ao tentar mudar o valor de um elemento o Numpy o converterá para a tipagem adequada quando possível.

In [30]:
arr[1] = 1.7334
arr

array([1, 1, 5])

In [31]:
arr[1] = "3"
arr

array([1, 3, 5])

In [32]:
'''
arr[1] = "3.2"
arr
Gera um erro!
'''

'\narr[1] = "3.2"\narr\nGera um erro!\n'

É interessante notar como funciona a alocação de memória para transformações particulares do array que podem afetar sua mutabilidade. Por exemplo, suponhamos que temos os arrays a, b e c todos criados a partir de transformações do vetor a.

In [33]:
a = np.arange(12, dtype="int64")
b = a.reshape(3, 4)
c = a[::2]
print(a)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  2  4  6  8 10]


O que acontece, neste caso, se eu alterar o vetor a?

In [34]:
a[0] = -1
print(a)
print(b)
print(c)

[-1  1  2  3  4  5  6  7  8  9 10 11]
[[-1  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[-1  2  4  6  8 10]


Veja que se altera os vetores b e c. Isso acontece porque na visão de memória esses vetores apontam para a mesma localização na RAM.

In [35]:
print(f"a: dtype={a.dtype} | shape={a.shape} | size={a.size} | itemsize={a.itemsize} | strides={a.strides}")
print(f"b: dtype={b.dtype} | shape={b.shape} | size={b.size} | itemsize={b.itemsize} | strides={b.strides}")

a: dtype=int64 | shape=(12,) | size=12 | itemsize=8 | strides=(8,)
b: dtype=int64 | shape=(3, 4) | size=12 | itemsize=8 | strides=(32, 8)


Da mesma forma o vetor c é uma representação especial do vetor a, na qual mudamos o valor de passo entre elementos do array.

In [36]:
print(f"a: dtype={a.dtype} | shape={a.shape} | size={a.size} | itemsize={a.itemsize} | strides={a.strides}")
print(f"c: dtype={c.dtype} | shape={c.shape} | size={c.size} | itemsize={c.itemsize} | strides={c.strides}")

a: dtype=int64 | shape=(12,) | size=12 | itemsize=8 | strides=(8,)
c: dtype=int64 | shape=(6,) | size=6 | itemsize=8 | strides=(16,)


Por fim é importante lembrar que tal como listas e dicionário, arrays são passados como referência em função, de forma que qualquer alteração no array feito dentro de uma função será carregada para fora da mesma.

In [37]:
def muda_a(a):
  a[1] = 12890
print(a)
muda_a(a)
print(a)
print(b)
print(c)

[-1  1  2  3  4  5  6  7  8  9 10 11]
[   -1 12890     2     3     4     5     6     7     8     9    10    11]
[[   -1 12890     2     3]
 [    4     5     6     7]
 [    8     9    10    11]]
[-1  2  4  6  8 10]


##**Operações**<br>
Como descrito anteriormente, Numpy é uma biblioteca de álgebra linear, de forma que suporta todas as operações vetoriais tradicionais.

In [38]:
np.random.seed(42)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
m1 = np.random.randint(1, 10, size=(3, 3))
m2 = np.random.randint(1, 10, size=(3, 3))

print(m1)
print(m2)

[[7 4 8]
 [5 7 3]
 [7 8 5]]
[[4 8 8]
 [3 6 5]
 [2 8 6]]


Soma

In [39]:
arr1 + arr2

array([5, 7, 9])

In [40]:
np.add(arr1, arr2)

array([5, 7, 9])

Subtração

In [41]:
arr1 - arr2

array([-3, -3, -3])

In [42]:
np.subtract(arr1, arr2)

array([-3, -3, -3])

Multiplicação (escalar)

In [43]:
arr1 * 2

array([2, 4, 6])

In [44]:
arr1 * 2.1

array([2.1, 4.2, 6.3])

In [45]:
np.multiply(arr1, 2)

array([2, 4, 6])

Multiplicação (element-wise)

In [46]:
arr1 * arr2

array([ 4, 10, 18])

In [47]:
np.multiply(arr1, arr2)

array([ 4, 10, 18])

Multiplicação (produto vetorial)

In [48]:
sum(arr1 * arr2)

32

In [49]:
arr1.dot(arr2)

32

In [50]:
np.dot(arr1, arr2)

32

Multiplicação (cruzada)

In [51]:
np.cross(arr1, arr2)

array([-3,  6, -3])

Multiplicação (matricial)

In [52]:
m1@m2

array([[ 56, 144, 124],
       [ 47, 106,  93],
       [ 62, 144, 126]])

In [53]:
np.matmul(m1, m2)

array([[ 56, 144, 124],
       [ 47, 106,  93],
       [ 62, 144, 126]])

Divisão

In [54]:
arr1 / arr2

array([0.25, 0.4 , 0.5 ])

In [55]:
np.divide(arr1, arr2)

array([0.25, 0.4 , 0.5 ])

Exponenciação

In [56]:
arr1 ** 2

array([1, 4, 9])

In [57]:
arr1 ** arr2

array([  1,  32, 729])

In [58]:
np.power(arr1, arr2)

array([  1,  32, 729])

Módulo de um vetor

In [59]:
sum(arr1 * arr1) ** 0.5

3.7416573867739413

In [60]:
np.linalg.norm(arr1)

3.7416573867739413

Determinante de uma matriz

In [61]:
np.linalg.det(m1)

-11.00000000000003

Matriz inversa

In [62]:
np.linalg.inv(m1)

array([[-1.        , -4.        ,  4.        ],
       [ 0.36363636,  1.90909091, -1.72727273],
       [ 0.81818182,  2.54545455, -2.63636364]])

Matriz transposta

In [63]:
np.transpose(m1)

array([[7, 5, 7],
       [4, 7, 8],
       [8, 3, 5]])

In [64]:
m1.T

array([[7, 5, 7],
       [4, 7, 8],
       [8, 3, 5]])

In [65]:
arr1.T

array([1, 2, 3])

Uma propriedade especial de arrays é o "broadcasting", na qual uma operação pode ser propagada entre arrays de diferentes tamanhos contanto que obedeçam algumas propriedades específicas. Por exemplo, podemos somar dois arrays de tamanhos diferentes, contanto que possamos "reproduzir" um deles para ficar com o tamanho do outro.

In [66]:
arr3 = np.array([1, 2, 3, 4])

In [67]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])

In [68]:
arr3 + arr1

array([[2, 4, 6],
       [5, 7, 9]])

In [69]:
arr3 * arr1

array([[ 1,  4,  9],
       [ 4, 10, 18]])

###**Representações**<br>
Há alguns elementos matemáticos que possuem representações especiais no Numpy.<br>
np.nan -> Not a Number, é a representação de um dado faltante.

In [70]:
arr = np.array([1, 2, np.nan, 4])
arr

array([ 1.,  2., nan,  4.])

In [71]:
np.isnan(arr)

array([False, False,  True, False])

In [72]:
np.zeros(3)/0

<ipython-input-72-2f7de20c6e27>:1: RuntimeWarning: invalid value encountered in divide
  np.zeros(3)/0


array([nan, nan, nan])

É importante destacar que None e NaN não são a mesma coisa. Not a Number indica um operação matemárica ou um dado númerico não existente dentro de um array, enquanto None é o objeto nulo do Python.

np.inf -> Infinito, representa valores infinitos.

In [73]:
arr = np.array([1, 2, np.inf, 4, -np.inf])
arr

array([  1.,   2.,  inf,   4., -inf])

In [74]:
np.isfinite(arr)

array([ True,  True, False,  True, False])

In [75]:
np.ones(3)/0

<ipython-input-75-c6764c1134a7>:1: RuntimeWarning: divide by zero encountered in divide
  np.ones(3)/0


array([inf, inf, inf])

Constantes numéricas:
- np.pi: 3.14 (constante PI)
- np.e: 2.72 (número de euler)

In [76]:
np.pi

3.141592653589793

In [77]:
np.e

2.718281828459045

###**Filtros**<br>
Uma particularidade interessante de arrays é a habilidade de realizar filtros de seus dados a partir de comparações booleanas.

In [78]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=10)
arr

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

Ao gerar uma comparação (tratando arrays como uma variável) o resultado é um array de booleanos com o resultado da comparação de cada elemento do array.

In [79]:
arr > 50

array([ True,  True, False,  True,  True, False,  True,  True,  True,
        True])

Essas comparações também aceitam os operadors lógicos and/or/not, entretanto os mesmos devem vir no formato &/|/~ (respectivamente) e, além disso, obrigatoriamente necessitam de () para cada operação lógica.

In [80]:
(arr > 50) & (arr < 75)

array([ True, False, False,  True,  True, False, False, False,  True,
        True])

O filtro do array ocorre ao passar uma comparação como parte da sintaxe de chaves, de forma que é como se estivessemos indexando o array onde o resultado da comparação lógica é verdadeiro.

In [82]:
arr[(arr > 50) & (arr < 75)]

array([51, 71, 60, 74, 74])

Uma função muito interessante criada com esse propósito é o where, na qual espera-se receber como primeiro input uma comparação e devolve como output os índices na qual a comparação é verdadeira.

In [83]:
np.where((arr > 50) & (arr < 75))

(array([0, 3, 4, 8, 9]),)

Alternativamente ainda podemos passar mais dois parâmetros para a função where, de tal forma que criaremos um novo array obtendo o segundo parâmetro como resultado onde a comparação é verdadeira e o terceiro onde a comparação é falsa.

In [85]:
np.where((arr > 50) & (arr < 75), "Papai Noel é top", "Papai Noel não é legal")

array(['Papai Noel é top', 'Papai Noel não é legal',
       'Papai Noel não é legal', 'Papai Noel é top', 'Papai Noel é top',
       'Papai Noel não é legal', 'Papai Noel não é legal',
       'Papai Noel não é legal', 'Papai Noel é top', 'Papai Noel é top'],
      dtype='<U22')

Nós inclusive conseguimos fazer alterações em arrays utilizando filtros.

In [86]:
arr[(arr > 50) & (arr < 75)] = -1
arr

array([-1, 92, 14, -1, -1, 20, 82, 86, -1, -1])

Além dos comparadores lógicos entre elementos, o numpy ainda contém agregadores lógicos tais com as funções nativas de python all e any, na qual checamos se todos (all) elementos de uma sequência são verdadeiros ou se algum (any) dos elementos são verdadeiros

In [87]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=10)

print(arr)
print((arr > 50) & (arr < 75))

print(all((arr > 50) & (arr < 75)))
print(np.all((arr > 50) & (arr < 75)))

print(any((arr > 50) & (arr < 75)))
print(np.any((arr > 50) & (arr < 75)))

[51 92 14 71 60 20 82 86 74 74]
[ True False False  True  True False False False  True  True]
False
False
True
True


A vantagem dos operadores do Numpy em contrapartida as funções do Python é a possibilidade de fazer isso em arrays multidimensionais, até mesmo selecionando eixos específicos.

In [88]:
arr.reshape(2, 5) < 70

array([[ True, False,  True, False,  True],
       [ True, False, False, False, False]])

In [90]:
np.all(arr.reshape(2, 5) < 70)

False

In [91]:
np.all(arr.reshape(2, 5) < 70, axis = 0)

array([ True, False, False, False, False])

Por fim, vale destacar que as mesmas regras de broadcast que se aplicam a operações matemáticas se aplicam à operadores lógicos.

In [92]:
arr.reshape(2, 5) > np.array([20, 30, 40, 50, 60])

array([[ True,  True, False,  True, False],
       [False,  True,  True,  True,  True]])

In [93]:
arr.reshape(2, 5, 1) > np.array([20, 30, 40, 50, 60])

array([[[ True,  True,  True,  True, False],
        [ True,  True,  True,  True,  True],
        [False, False, False, False, False],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False]],

       [[False, False, False, False, False],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

###**Funções**<br>
Ao longo das sessões anteriores nós já vimos uma série de funcionalidades úteis que podem ser utilizadas para realizar cálculos especiais, como np.cross, np.isnan e assim por diante. O Numpy é recheado dessas funções que nos ajudam a realizar todo o tipo de cálculo, como álgebra linear, estatística, funções matemáticas e mais.

Poderíamos passar horas apenas só falando sobre essas diferentes funções, mas a verdade é que nós vamos nos familiarizando com elas conforme vamos aplicando-as em diferentes contexto.

Abaixo nós agrupamos as funções que esperamos encontrar mais recorrentemente em nossos cálculos e colocamos alguns exemplos de como elas funcionam.

In [94]:
np.random.seed(42)
A = np.random.normal(loc=5, size=(5, 3))
B = np.random.choice(["A", "B", "C"], size=(5,3))
C = np.array([0, 1, 2, 0, 4, 5])
D = np.random.normal(size=(5, 3))

**Agregação**:
- np.mean: Calcula a média
- np.median: Calcula a mediana
- np.min: Calcula o valor mínimo
- np.max: Calcula o valor máximo
- np.std: Calcula o desvio-padrão
- np.var: Calcula a variância
- np.percentile: Calcula o percentil específicado
- np.sum: Calcula a soma de todos os elementos
- np.count_nonzero: Realiza a contagem dos elementos não nulos do array
- np.unique: Obtém os valores únicos de um array

In [95]:
print(A, np.mean(A))

[[5.49671415 4.8617357  5.64768854]
 [6.52302986 4.76584663 4.76586304]
 [6.57921282 5.76743473 4.53052561]
 [5.54256004 4.53658231 4.53427025]
 [5.24196227 3.08671976 3.27508217]] 5.010348524333337


In [96]:
print(A, np.mean(A, axis=1))

[[5.49671415 4.8617357  5.64768854]
 [6.52302986 4.76584663 4.76586304]
 [6.57921282 5.76743473 4.53052561]
 [5.54256004 4.53658231 4.53427025]
 [5.24196227 3.08671976 3.27508217]] [5.33537946 5.35157984 5.62572439 4.87113753 3.8679214 ]


In [97]:
print(A, np.percentile(A, 0.25))

[[5.49671415 4.8617357  5.64768854]
 [6.52302986 4.76584663 4.76586304]
 [6.57921282 5.76743473 4.53052561]
 [5.54256004 4.53658231 4.53427025]
 [5.24196227 3.08671976 3.27508217]] 3.093312439767269


In [98]:
print(B, np.unique(B))

[['C' 'C' 'B']
 ['C' 'B' 'B']
 ['C' 'B' 'C']
 ['C' 'A' 'C']
 ['A' 'C' 'C']] ['A' 'B' 'C']


In [99]:
print(C, C.shape, np.count_nonzero(C))

[0 1 2 0 4 5] (6,) 4


**Transformação**:

- np.ceil: Arredonda os valores de um array para cima
- np.floor: Arredonda os valores de um array para baixo
- np.round: Arredonda os valores de um array para as casas decimais desejadas
- np.trunc: Remove as casas decimais do valor numérico
- np.abs: Calcula o valor absoluto dos elementos
- np.sign: Obtém os sinais dos números de um array

In [100]:
print(A, np.ceil(A))

[[5.49671415 4.8617357  5.64768854]
 [6.52302986 4.76584663 4.76586304]
 [6.57921282 5.76743473 4.53052561]
 [5.54256004 4.53658231 4.53427025]
 [5.24196227 3.08671976 3.27508217]] [[6. 5. 6.]
 [7. 5. 5.]
 [7. 6. 5.]
 [6. 5. 5.]
 [6. 4. 4.]]


In [101]:
print(A, np.round(A, 2))

[[5.49671415 4.8617357  5.64768854]
 [6.52302986 4.76584663 4.76586304]
 [6.57921282 5.76743473 4.53052561]
 [5.54256004 4.53658231 4.53427025]
 [5.24196227 3.08671976 3.27508217]] [[5.5  4.86 5.65]
 [6.52 4.77 4.77]
 [6.58 5.77 4.53]
 [5.54 4.54 4.53]
 [5.24 3.09 3.28]]


In [102]:
print(A, np.trunc(A))

[[5.49671415 4.8617357  5.64768854]
 [6.52302986 4.76584663 4.76586304]
 [6.57921282 5.76743473 4.53052561]
 [5.54256004 4.53658231 4.53427025]
 [5.24196227 3.08671976 3.27508217]] [[5. 4. 5.]
 [6. 4. 4.]
 [6. 5. 4.]
 [5. 4. 4.]
 [5. 3. 3.]]


In [103]:
print(D, np.sign(D))

[[-0.56228753 -0.60025385  0.94743982]
 [ 0.291034   -0.63555974 -1.02155219]
 [-0.16175539 -0.5336488  -0.00552786]
 [-0.22945045  0.38934891 -1.26511911]
 [ 1.09199226  2.77831304  1.19363972]] [[-1. -1.  1.]
 [ 1. -1. -1.]
 [-1. -1. -1.]
 [-1.  1. -1.]
 [ 1.  1.  1.]]


**Função Matemática**:

- np.exp: Realiza a exponenciação dos elementos
- np.log: Aplica o log sobre os elementos
- np.expm1: Aplica a função exp(x) - 1 sobre os elementos
- np.log1p: Aplica a função log(x + 1) sobre os elementos
- np.power: Eleva os elementos do array a uma potência
- np.sqrt: Extraí a raíz quadrada dos números de um array
- np.sin/cos/tan: Aplica a função seno/cosseno/tangente sobre os elementos
- np.asin/acos/atan: Aplica a função de arc seno/cosseno/tangente sobre os elementos

In [104]:
np.log(A)

array([[1.70415049, 1.58139551, 1.73124635],
       [1.87533897, 1.5614752 , 1.56147864],
       [1.88391511, 1.75222739, 1.51083796],
       [1.7124565 , 1.51217393, 1.51166415],
       [1.65669591, 1.12710896, 1.18634296]])

In [105]:
np.sin(D)

array([[-0.53312293, -0.56485197,  0.81192363],
       [ 0.2869429 , -0.59362805, -0.85291936],
       [-0.16105093, -0.50867818, -0.00552783],
       [-0.22744241,  0.37958614, -0.95364337],
       [ 0.88754655,  0.35534171,  0.92971555]])

**Elemento a Elemento**
- np.diff: Obtém a diferença entre valores sequenciais do array
- np.cumsum: Obtém a soma dos valores cumulativos
- np.cummin: Obtém o valor mínimo cumulativo do array
- np.cummax: Obtém o valor máximo cumulativo do array
- np.cumprod: Obtém o valor produto cumulativo do array

In [106]:
print(C, np.diff(C))

[0 1 2 0 4 5] [ 1  1 -2  4  1]


In [107]:
print(C, np.cumsum(C))

[0 1 2 0 4 5] [ 0  1  3  3  7 12]
