<a href="https://colab.research.google.com/github/joaoholandaa/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Numpy**

In [1]:
import os
import numpy as np
import pandas as pd

from pathlib import Path

%config Completer.use_jedi = False

##**Criação**<br>
Array são objetos que armazenam estruturas sequênciais de dados de tipo e tamanhos determinados que apontam para uma sequência de dados na memória RAM. Em Python, a biblioteca que lida com essas estruturas é o Numpy que não só oferece as funcionalidades clássicas de um array (que pode ser vistas em C, C++, Java...), mas também propriedades vetoriais utilizadas em operações em álgebra linear. <br> <br>
Criar um array é uma tarefa simples, que pode ser realizada por meio de uma lista como abaixo.

In [2]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [3]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

Ao fazer isso estaremos alocando os valores selecionados dentro da RAM do computador em endereços sequênciais, igualmente espaçados de acordo com o tipo de dado do array.<br><br>

Dado isso, é fácil perceber que um array tem as seguintes características que podem ser acessadas na forma de atributos deste objeto:

- dtype: O tipo de dados do array
- shape: O tamanho do array em linhas e colunas
- size: O tamanho do array em quantidade de elementos
- itemsize: O consumo de memória de cada elemento do array (em bytes)
- strides: Uma distancia em bytes entre os elementos armazenados na memória

In [4]:
print(
    f"array: dtype={array.dtype} | shape={array.shape} | size={array.size} "
    f"| itemsize={array.itemsize} | strides={array.strides}"
)

print(
    f"matriz: dtype={matriz.dtype} | shape={matriz.shape} | size={matriz.size} "
    f"| itemsize={matriz.itemsize} | strides={matriz.strides}"
)

array: dtype=int64 | shape=(5,) | size=5 | itemsize=8 | strides=(8,)
matriz: dtype=int64 | shape=(2, 3) | size=6 | itemsize=8 | strides=(24, 8)


Dado que inicializações de diferentes tipos de array são bastante comuns, a biblioteza contém uma série de funcionalidades que permitem criar arrays com diferentes tipos de dados. <br><br>
**np.zeros** -> Cria um array preenchido com zeros.

In [5]:
np.zeros(shape=(3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

**np.ones** -> Cria um array preenchido com "um's".

In [6]:
np.ones(shape=(3, ))

array([1., 1., 1.])

**np.eye** -> Cria a matriz identidade com o tamanho especificado.

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**np.arange** -> Mesma coisa que a função range, só que para arrays.

In [8]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

**np.linspace** -> Cria um array entre dois números espaçados linearmente.

In [9]:
np.linspace(5, 10, num=5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

**np.logspace** -> Cria um array entre dois números espaçados logaritmicamente.

In [10]:
np.logspace(0, 1, 3)

array([ 1.        ,  3.16227766, 10.        ])

**np.random.int** -> Cria um array de valores aleatórios entre um valor menor e maior (exclusivo).

In [11]:
np.random.randint(0, 10, size=(5,5))

array([[2, 0, 6, 4, 6],
       [9, 7, 9, 4, 5],
       [7, 3, 9, 3, 1],
       [6, 1, 9, 9, 3],
       [0, 6, 2, 2, 9]])

**np.random.normal** -> Cria um array aleatório com valores baseados em uma distribuição normal.

In [12]:
np.random.normal(1, 2, 10)

array([ 2.78330553,  1.65785123,  2.32848251, -0.62132574,  2.6138556 ,
        4.24364608, -0.75914664,  1.83944802,  1.94965863,  0.68709567])

É interessante notar que algumas dessas funções não permitem passar o tamanho do array (como o np.arange), por muitas vezes é comum combiná-las com o método reshape.

In [13]:
a = np.arange(12)
a = a.reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

##**Tipagem**<br>
Uma das diferenças mais gritantes entre arrays e listas é sua tipagem. Enquanto listas podem conter múltiplos tipos de dados (inteiros, strings, floats, etc) arrays tendem a tipagem fixa e tal tipagem pode ser modificda utilizando o método astype.

In [14]:
arr = np.array([1, 2, 3])
print(arr.dtype, arr)

int64 [1 2 3]


In [15]:
arr = np.array([1, 2, 3])
arr = arr.astype("float")
print(arr.dtype, arr)

float64 [1. 2. 3.]


In [16]:
arr = np.array([1, 2, 3], dtype=np.uint8)
print(arr.dtype, arr)

uint8 [1 2 3]


In [17]:
arr = np.array(["olá", 2.1, [2, 3, 4]], dtype="object")
arr.shape

(3,)